name: SixFiveZeroTwo
version: 0.0.1
description: Emulator for the 6502 CPU.

dependencies:
- base >= 4.7 && < 5
- listsafe
- transformers
- exceptions

library:
  source-dirs: src
  exposed-modules:
  - CPU
  - Instruction
  - Computer

tests:
  stack-test:
    main: Test.hs
    source-dirs: test/
    dependencies:
    - stm
    - mtl
    - containers
    - random
    - async
    - SixFiveZeroTwo
